export const iconList = [
  { name: "analyzing", value: "icon-analyzing" },
  { name: "avenue", value: "icon-avenue" },
  { name: "bridge", value: "icon-bridge" },
  { name: "building", value: "icon-building" },
  { name: "calander", value: "icon-calander" },
  { name: "check", value: "icon-check" },
  { name: "clock", value: "icon-clock" },
  { name: "crown", value: "icon-crown" },
  { name: "danger", value: "icon-danger" },
  { name: "envelope", value: "icon-envelope" },
  { name: "equality", value: "icon-equality" },
  { name: "final-flag", value: "icon-final-flag" },
  { name: "form", value: "icon-form" },
  { name: "gurd", value: "icon-gurd" },
  { name: "gym", value: "icon-gym" },
  { name: "hamburgur", value: "icon-hamburgur" },
  { name: "hammer", value: "icon-hammer" },
  { name: "hand-shake", value: "icon-hand-shake" },
  { name: "hospital", value: "icon-hospital" },
  { name: "human-right", value: "icon-human-right" },
  { name: "kids-house", value: "icon-kids-house" },
  { name: "line", value: "icon-line" },
  { name: "location", value: "icon-location" },
  { name: "location-02", value: "icon-location-02" },
  { name: "love-4223", value: "icon-love-4223" },
  { name: "manager", value: "icon-manager" },
  { name: "mike", value: "icon-mike" },
  { name: "office-location.path1", value: "icon-office-location .path1" },
  { name: "office-location.path2", value: "icon-office-location .path2" },
  { name: "office-location.path3", value: "icon-office-location .path3" },
  { name: "paper-plan", value: "icon-paper-plan" },
  { name: "phone", value: "icon-phone" },
  { name: "quotes", value: "icon-quotes" },
  { name: "quotes-left", value: "icon-quotes-left" },
  { name: "quotes-right", value: "icon-quotes-right" },
  { name: "resource", value: "icon-resource" },
  { name: "rise-hand", value: "icon-rise-hand" },
  { name: "school", value: "icon-school" },
  { name: "search-svgrepo-com-1", value: "icon-search-svgrepo-com-1" },
  { name: "star", value: "icon-star" },
  { name: "sweet-hone", value: "icon-sweet-hone" },
  { name: "target-3696", value: "icon-target-3696" },
  { name: "tips-bulb", value: "icon-tips-bulb" },
  { name: "tree", value: "icon-tree" },
  { name: "vallot", value: "icon-vallot" },
  { name: "water-drop", value: "icon-water-drop" },
  { name: "wheel", value: "icon-wheel" },
  { name: "winner-cup", value: "icon-winner-cup" },
  { name: "women-leader", value: "icon-women-leader" }
];